# config coming soon...
#
# Don't edit plugin version!
# version: "0.0.2"
#
# Display item count and name
# default-format: "{item_count}x {item_name}"
#
# Enable DisplayItem in these worlds
# worlds:
# - "world"
